apiVersion: v1
kind: Service
metadata:
  name: {{ template "dependency-track.fullname" . }}
  labels:
{{ include "dependency-track.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "dependency-track.name" . }}
    release: {{ .Release.Name }}
